#!/bin/bash

if [ "${1}" == ".args" ] || [ "${1}" == ".description" ]; then
	exit 0
fi

if [ "${LIB_PATH}" != "" ]; then
	exec ${LIB_PATH} "$@"
else
	. .errors
	echo "LIB_PATH is not set for" >&2
	handleError 1 "$@"
	exit 1
fi
