#!/bin/bash

args="<string> <search string>"
description="Gets everything before the beginning of the search string"

. .cmd

requires 2 arguments

if [[ "${1}" == *"${2}"* ]]; then
	index=`string indexof "${1}" "${2}"`
	if [ $index -lt 0 ]; then
		echo "${1}"
	else
		echo "${1:0:index}"
	fi
else
	echo "${1}"
fi
