#!/bin/bash

args="<string> <search string>"
description="Returns true or false if the string ends with the search string"

. .cmd

requires 2 arguments

if [[ "${1}" == *"${2}" ]]; then
	echo "true"
else
	echo "false"
fi
